apiVersion: apps/v1
kind: Deployment
metadata:
  name: sakila-service-deployment
  namespace: my-name-space
  labels:
    app: sakila-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sakila-app
  template:
    metadata:
      labels:
        app: sakila-app
    spec:
      containers:
      - name: sakila-container
        image: gireesh26/sakila
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: sakila-service
  namespace: my-name-space
spec:
  selector:
    app: sakila-app
  ports:
    - protocol: "TCP"
      port: 8888
      targetPort: 8888
